spring:
  application:
    name: backend

nasa:
    api-key: ${NASA_API_KEY}
    baseURL: "https://api.nasa.gov"

---
spring:
    config:
        activate:
            on-profile: dev



---
spring:
    config:
        activate:
            on-profile: prod

---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/telemetry
        driver-class-name: org.postgresql.Driver
        username: telemetry
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true
